[project]
name = "prediccioncontransformers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "keras>=3.9.2",
    "matplotlib>=3.10.1",
    "numpy",
    "tensorflow>=2.19.0",
]
